### ISSUE TITLE
Source dirs priority issue when setting breakpoints

### ISSUE THREAD

**Issue by elsassph** [rokucommunity/roku-debug#9]
Our project is organised (for some reason):
```
project/src/components/...
project/src/source/main.brs
```
So `bsconfig.json` has: `rootDir: "."` and `sourceRoot: "src/"` 

And VSCode `launch.json` for debugging has: `"sourceDirs": [ "${workspaceFolder}/src" ]`

Now the problem is that `BreakpointManager` calls `LocationManager.getStagingLocations` with source roots in this order:
- `project/`
- `project/src/`

which **crashes** during breakpoint insertion because it tries to create a breakpoint in `project/out/.staging/src/source/main.brs`

**Comment by TwitchBronBron** [comment]
sourceRoot is only used when using BrighterScript to transpile your project from a staging directory. The extension does not use BrighterScript for these purposes. From what I can tell, you should delete sourceRoot and sourceDirs, and set rootDir to "./src".

Unless you are using a custom build process, then BrighterScript, and then having the extension launch.  BrighterScript for

**Comment by TwitchBronBron** [comment]
So just to be clear, if this is your project structure:
 - project/
    - src/
      - components/
       - source/

And you aren't doing any type of pre-build, then your launch config (and bsconfig) should look like this:

```javascript
{
    "rootDir": "./src",
}
```
That tells the language server (and roku-deploy) to treat `project/src` as the root of your project.

**Comment by elsassph** [comment]
I'll try again by changing `rootDir`, but we have resources and manifest outside of `src`.

**Comment by elsassph** [comment]
So you're right I can make it work with `rootDir: "src"` and in the files moving `../manifest` into place.

I had issues because `{ src: "../manifest", dest: "." }` causes unintuitive "can not unlink 'out/.roku-deploy-staging`" errors, but it works with `{ src: "../manifest", dest: "manifest" }`.

I know I should change our project structure but we have half a dozen of projects with this odd organisation.

**Comment by TwitchBronBron** [comment]
`{ src: "../manifest", dest: "." }` is invalid, and `{ src: "../manifest", dest: "manifest" }` is correct. Here's the [rule](https://github.com/rokucommunity/roku-deploy#-src-dest--object-rules) from roku-deploy:
![image](https://user-images.githubusercontent.com/2544493/87146121-78657300-c278-11ea-818c-4661121a16a8.png)

As far as the cryptic error message, it's pretty hard in roku-deploy to know what you intended to do until runtime, since we support globs. But for single file paths, I think we might be able to better detect that. I'll open an issue on roku-deploy and see what we can do. 

So, is this issue resolved for you?

**Comment by elsassph** [comment]
Yes I'm good now.
